version: "3.9"
services:
  webapi:
    depends_on:
      - postgres
    build: .
    ports:
      - "3000:3000"
    env_file:
      - ./.env
  postgres:
    image: postgres
    ports:
      - "5432:5432"
    env_file:
      - ./.env
